# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5f6c2114964f1c4cac7f0a6c997682c564ce18767f555d0e7788ac21788b27a9cac0bf0778c0d5bb0bef76688cd115ebb1d775f443f182b8ba00d57cb1753b31

test:
  secret_key_base: af61ac1935bf95d2f3e1189dded808d1b7813d139030c0e43fb82be8b657a15c40dac33b9fc5007f0b3c42f02dc65d0e1e0d9152eef30687c7dea392a1fbcb7e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
